import { Poppins } from "next/font/google";
import { Box, Typography } from "@mui/material";
import ThemeProviderComponent from "./ThemeProvider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Pantry Tracker",
  description: "Generated by create next app",
};

const Header = () => (
  <Box
    component="header"
    sx={{
      bgcolor: 'background.paper',
      padding: '0.75rem',
      textAlign: 'start',
      paddingLeft: '3rem',
      top: 0,
      width: '100%'
    }}
  >
    <Typography
      variant="h6"
      sx={{
        color: 'text.primary',
        fontWeight: 'bold',
        fontSize: '1.5rem'
      }}
    >
      Pantry Tracker
    </Typography>
  </Box>
);

const Footer = () => (
  <Box
    component="footer"
    sx={{
      p: 2,
      textAlign: 'center',
      bgcolor: 'background.default'
    }}
  >
    <Typography variant="body2">
      &copy; 2024 Pantry Tracker. All rights reserved.
    </Typography>
  </Box>
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} style={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh'
      }}>
        <ThemeProviderComponent>
          <Header />
          <Box component="main" sx={{ flex: '1 0 auto' }}>{children}</Box>
          <Footer />
        </ThemeProviderComponent>
      </body>
    </html>
  );
}
